### ISSUE TITLE
problematic conversion of Parentheses and other symbols

### ISSUE THREAD

**Issue by kilon** [pillar-markup/pillar-mode#5] opened 2014-06-27 12:40 UTC
For example I have this text from section 4.4 of PBE , "The characters [, ], ( and ) delimit distinct areas" and its is converted to 

"The characters ==[}, \ct{]==, ==(} and \ct{)==
delimit distinct areas"

besides the weird conversion also observed that it inserts a newline after \ct{)==

I assume this is undesirable behaviour.

**Comment by DamienCassou** [comment] 2014-06-27 13:28
I can't reproduce. Please update your version of pillar-mode and make sure you load the latest one in emacs (go to the pillar-latex2pillar.el file and type `M-x eval-buffer`. I'm closing this bug for now, feel free to reopen if you have more information.

**Closed as completed by DamienCassou** 2014-06-27 13:28 UTC
